general:
  num: 4
  name: ga47_1o72_0
  description: 单胞：Ga；这是完美的Ga单质晶体；这里计算了其不带电的总能量（0）
  
tasks:
  - str_opt_0:
      run: False
      INCAR: INCAR_str_opt_0
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: POSCAR

  - hse06_scf_0_0.35:
      run: False
      INCAR: INCAR_hse06_scf_0_0.35
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: str_opt_0/CONTCAR
  
  - hse06_scf_0_0.32:
      run: True
      INCAR: INCAR_hse06_scf_0_0.32
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: str_opt_0/CONTCAR

