general:
  num: 4
  name: Cu_{Ga(I)}
  description: 原超胞：Ga48O72；它有一个Cu_{Ga(I)}缺陷，是第7个Ga；这里计算了其不带电的总能量（0）和带一个负电的总能（-1）
  
tasks:
  - str_opt_0:
      run: True
      INCAR: INCAR_str_opt_0
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: Mg.poscar

  - pbe_0:
      run: True
      INCAR: INCAR_pbe_0
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: str_opt_0/CONTCAR

  - hse06_0:
      run: True
      INCAR: INCAR_hse06_0
      KPOINTS: KPOINTS
      POTCAR: POTCAR
      POSCAR: str_opt_0/CONTCAR
      WAVECAR: pbe_0/WAVECAR
      CHGCAR: pbe_0/CHGCAR
      CHG: pbe_0/CHG